variables:
    GIT_SUBMODULE_STRATEGY: recursive

cache:
    paths:
        - target/

coverage:
    stage: test
    script:
      - cargo tarpaulin --exclude-files "include/*" --exclude-files "tests/*" -o Html
    artifacts:
        expire_in: 8 weeks
        paths:
            - tarpaulin-report.html
    timeout: 10m
