[package]
name = "hydra"
version = "0.1.0"
authors = ["David Schatz <david.schatz@tu-ilmenau.de>"]
edition = "2018"

[dependencies]
openssl-sys = "^0.9"
openssl = "^0.10"
hex = "^0.4"
tonic = "^0.2"
prost = "^0.6"

[build-dependencies]
cmake = "^0.1"
tonic-build = "^0.2"
